version : "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: app
      APP_KEY: "TypCz2R4/meiq4oH+JJkilFdf8vIf7ejpCdMAwpEwLk="
      ISSUER: "salty-files-1234"
    volumes:
      - .:/var/app
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33060:3306"
